#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyNewProject.Resource", IsApplication=true)]

namespace MyNewProject
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonReportProblemStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040008
			public const int BackToMainMenu = 2130968584;
			
			// aapt resource value: 0x7f04000e
			public const int Exit = 2130968590;
			
			// aapt resource value: 0x7f040003
			public const int NextButtonS = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int TakeAPhoto = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int comment = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int editText = 2130968577;
			
			// aapt resource value: 0x7f040009
			public const int imageView = 2130968585;
			
			// aapt resource value: 0x7f04000f
			public const int linearLayout1 = 2130968591;
			
			// aapt resource value: 0x7f04000b
			public const int loadedPhotos = 2130968587;
			
			// aapt resource value: 0x7f040007
			public const int progressBar1 = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int relativeLayout1 = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int reportProblem = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int seeOnMap = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int solvedProblems = 2130968589;
			
			// aapt resource value: 0x7f040000
			public const int textOverEdit = 2130968576;
			
			// aapt resource value: 0x7f040010
			public const int textView2 = 2130968592;
			
			// aapt resource value: 0x7f040005
			public const int uploadFromgGallery = 2130968581;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddComment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddPhotos = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LoadedPhotos = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int OnLoadedPhotosClickScreen = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int StartScreen = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
